### ISSUE TITLE
.dat file 

### ISSUE THREAD

**Issue by jayp84847** [braindotai/Facial-Landmarks-Detection-Pytorch#2]
Yet I am working on project with dlib 68 face landmarks. But its not as stable as this module. I am using 68_face_landmarks.dat file in my project. But can you guide how can I make ".dat" file with this module. Or can you please share ".dat" file for this module.

**Comment by braindotai** [comment]
Yes, this model is far more accurate than the dlib's one.
Though I'm not sure if the conversion of torch's inference to `.dat` file is possible.
I'd suggest you use `torch` only if all you want to do is running a python file.

**Comment by jayp84847** [comment]
Are you using dlib or any other? Cause your landmarks is also very stable than dlib 68 face landmarks. Can you please share .dat file of your dataset. I really need it.

**Comment by braindotai** [comment]
No dlib is used in the project, and as I said converting a torch inference to dlib is not possible. Kindly use the model I've provided to create the script which works with torch inference.

**Comment by jayp84847** [comment]
Yet I am using dlib in unity3d with opencv. Can you guide me how can use
your module in unity3d with c# or with any third party? Any suggestions?

**Comment by braindotai** [comment]
I've no clue regarding that.

**Comment by jayp84847** [comment]
Ok thank you for your response.😊

**Comment by jayp84847** [comment]
Can you guide me haw can I make dlib 68 face landmarks as stable as you or
any suggestions to make it more stable.
